apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t7wsg1nre-nodejs
  janus-idp.io/tekton: t7wsg1nre-nodejs
  backstage.io/kubernetes-id: t7wsg1nre-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t7wsg1nre-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
